thinca/vim-quickrun

autoload/quickrun.vim

nimの一時ファイル実行がエラーになっていたのでデフォルトの設定にtempfileを追加しました。
Nimのファイルは数字始まりNG で拡張子 .nim が必要なのですが、自分の環境（Ubuntu 14.04, vim 7.4.580）ではtempname()が返すファイル名が数字のみのため実行できませんでした。
一時ファイル名の前後を変更するようにして対応しました。
しばらく自分で使った限りでは問題なかったのですが、他の環境（Windows等）では試せていません。
他の環境で問題があるかもしれないので（ないとは思っているのですが）、別のPRにさせていただきました。
ご確認よろしくお願いいたします。

Add tempfile config for nim

---

autoload/quickrun.vim

`-jar` オプションは `-d` に名前変更になった様なので修正しました。
あと `C:\Program Files` でも動く様にしてあります。

Fix command for kotlin. Option -jar is no longer exists.

---

autoload/quickrun.vim

デフォルトでエラーメッセージに色が付けられてしまってエスケープシーケンスが混じってしまっていたので修正しました．
あと，`run` サブコマンドでコンパイル + 実行を一気にやってくれるようになったのでそちらを使うようにしました．

Crystal: Disable colorful output

---

autoload/quickrun.vim

rust の Cargo 用の設定を追加しました．
Cargo は rust に標準添付のビルドシステムで，コマンド一発でビルドおよび実行ができます．rust のプロジェクト内だとファイル単体でコンパイルできないことがほとんどのため，Cargo 経由で実行するのが便利なので設定してみました．

Added 'rust/cargo' config

---

autoload/quickrun/runner/vimproc.vim

`runner/vimproc` を介して重い処理を実行した時に、
vimproc の `s:runner.run()` は `stdout` と `stderr` の 2度 read_timeout を迎えることになります。
現在、vimproc ではデフォルトの read_timeout は 100ms に設定されているため、
この時間以内に処理が完了しない場合は必ず 200ms 待つことになります。
重い処理を実行するとあらかじめわかっている場合のために
オプションとして read_timeout を指定できるようにするのはいかがでしょうか。
なお、初期値には 65535 と大きな値を指定していますが、
vimproc はデフォルト値より大きな値が指定された場合は無視しているので影響はありません。
(十分大きな値を指定しただけですので、特に意味はありません)

Add read_timout option to runner/vimproc

---

autoload/quickrun.vim

実行した後にコンパイル済みの js ファイルが残ったままになっていたので削除するようにしました．

[TypeScript] Sweep compiled .js file

---

autoload/quickrun.vim

Hi, 
I love your plugin. I use it to show the plugins of a shell. I use fish as a default shell, so I would like this option to be included. This commit should be everything one needs. Please merge it into master.

Add support for the fish shell (www.fishshell.com) 

---

autoload/quickrun.vim

vimprocを使った時にエラーが出たんで直しました。ついでにdosbatchはWin環境限定と思いますので、cp932で文字化け回避しています。

Fix dosbatch

---

autoload/quickrun.vim

`tmux` quickrun config extracted from @rhysd [`.vimrc`](https://github.com/rhysd/dotfiles/blob/master/vimrc#L2262-L2266) file, if accepted I can safely remove this line from my `.tmux.conf`
```tmux
bind r source-file ~/.tmux.conf \; display "Reloaded ~/.tmux.conf"
```

Add tmux config.

---

autoload/vital/_quickrun.vim
autoload/vital/_quickrun/ConcurrentProcess.vim
autoload/vital/_quickrun/Data/String.vim
autoload/vital/_quickrun/Prelude.vim
autoload/vital/_quickrun/Process.vim
autoload/vital/_quickrun/System/File.vim
autoload/vital/_quickrun/System/Filepath.vim
autoload/vital/_quickrun/Vim/ViewTracer.vim
autoload/vital/quickrun.vital

vital.vimのconcprocにて、ごくまれに (具体的には最も再現しやすいコード例でも1/10くらいの発生率) `is_done()`直前に行われたstdout/stderr出力が無視されるいやらしいバグがありました。vitalの15995127a79e856ee58eebb102a2ad61fbf7a61cで修正したので、それをquickrunに反映。
scalaや(neoclojure未使用での)clojureのquickrunに良い影響があります。

Bugfix: concproc ignores output rarely

---

autoload/quickrun/runner/job.vim

`callback` と `exit_cb` の順番は保証されていないため、環境によっては `exit_cb` の後に `callback` が実行されることがあり、`exit_cb` 後に出力された内容が捨てられてしまいます。
`close_cb` で channel の close を確認してから runner を終了する必要があります。

Fix job-runner termination

---

autoload/quickrun.vim

idrisは依存型をとてもサポートした言語で、構文など色々Haskellに似ています :dog2:
- - -
以下は参考までに 👍 
- [Idris | A Language with Dependent Types](https://www.idris-lang.org/)
- [Getting Start](http://docs.idris-lang.org/en/latest/tutorial/starting.html)
- [Idrisが間もなくバージョン1.0に](https://www.infoq.com/jp/news/2017/01/idris-approaching-10)

Support idris

---

autoload/quickrun/hook/eval.vim

現状、 hook/eval/template を利用した時、一時ファイル名として問答無用で `a:session.tempname()` が利用されています。
この `a:session.tempname()` は g:quickrun_config.[filetype].tempfile を全く気にしないので、特にここでファイルの拡張子を指定していてもそれが無視されてしまいます。これにより例えば C++ などでは出力先ファイル名とソースファイル名が同一になってしまい、正常に実行できなくなります。
対処法としては、 
1. Session.tempname 内で tempfile を展開するようにする。
1. 予め展開したものを `a:session.tempname()` に渡して登録させる (部分選択時の動作はこちら？) 。
のいずれかが考えられますが、影響範囲を考えてとりあえず 2 で対応してみました。

Fix quickrun/hook/eval to expand config.tempfile

---

autoload/quickrun/outputter/loclist.vim
autoload/quickrun/outputter/quickfix.vim

If buffer is modified, the error list in quickfix points to the temporally file.
This PR will replace the temporally filename to bufname.
And fix lnum by region.
未保存状態で実行した場合 quickfix への出力はテンポラリファイルを示しているため、元のバッファを示すように修正します。また、リージョンを実行した場合は行番号を補正します。

Replace temporally filename to bufname in quickfix.

---

autoload/quickrun/hook/output_encode.vim
doc/quickrun.jax
doc/quickrun.txt

設定 `{'hook/output_encode/fileformat': 1}`  により、出力中の改行を正規化します。

Convert result fileformat.

---

autoload/quickrun.vim

[ts-node](https://github.com/TypeStrong/ts-node) is a CLI tool like `node` command, but can run TypeScript code directly.
This PR makes vim-quickrun prefer `ts-node` to `tsc` because `ts-node` does not need to create a temporary file (compile code on the fly). If `ts-node` is not installed, this PR does not break previous behavior. It falls back into `tsc`.

typescript: Use ts-node if possible

---

autoload/quickrun/runner/vimproc.vim
doc/quickrun.jax
doc/quickrun.txt

`runner/vimproc` でコマンドがパイプを含む場合、どの位置の終了コードを最終結果とするかを指定できるようにします。
設定名と値は bash または zsh の `$pipestatus` と `set -o pipefail` に由来します。
```vim
" cat, grep は無視して常に "%c" コマンドの終了コードを利用する。
let b:quickrun_config = {
\  "exec": "cat foo.txt | %c %o %s %a | grep bar",
\  "runner/vimproc/pipe_status_index": 1,
\}
" 全てのコマンドから、最後(最も右側)の 0 以外の終了コードを利用する。
" (全てのコマンドが成功(終了コード 0)した場合のみ 0 が返る。)
let b:quickrun_config = {
\  "exec": "preproc %s | %c %o %s %a | postproc",
\  "runner/vimproc/pipe_status_index": "pipefail",
\}
```

Add option `runner/vimproc/pipe_status_index`.

---

autoload/quickrun.vim

Prolog の処理系 SWI prolog と GNU prolog を追加しました。
テスト用に使ったスクリプトです。
```prolog
main :-
write('hello'),nl,
write('world'),nl,
nl,
write('prolog')
% ,halt.    % halt がない場合もある場合も必ず終了するようにする
.
:- initialization(main).
```
Prolog はスクリプトで `halt.` がなければ Prolog のプロンプト (REPL) が立ち上がるので、
それぞれ `-g` (SWI), `--query-goal` (GNU) で 終了するようにしています。
追記：
確認環境：Windows Subsystem Linux (Debian 9.5)

Add prolog config (prolog/swi, prolog/gnu)

---

autoload/quickrun.vim

Flag `--enable-type-checks` isn't supported anymore.

Fix Dart support

---

autoload/quickrun.vim

ts-node8 had remove the `--compilerOption`.

upgrade the cmdopt on ts-node8

---

autoload/quickrun.vim

This PR is treat below:
https://teratail.com/questions/62932
- clang/clang++ in windows exec add `.exe`
- clang/clang++, gcc/g++ in windows file clean hook add `.exe`
Note:
remain question
- c   priory gcc/clang
- cpp priory clang++/g++
It has reason for do not same priority order?

fix: treat windows clang/clang++ build and others

---

autoload/quickrun.vim

実行対象の tempfile に拡張子 `.ts` がないと JavaScript として解釈されるようで、TypeScript 側の予約語等を使うとエラーになります。
Deno 1.9.2 (2021-04-28 時点の最新) で確認。

Fix typescript/deno config

---

autoload/quickrun.vim

Recently, F# is running on dotnet command. But vim-quickfix does not support it.
```vim
Plug 'fsharp/vim-fsharp'
```
No way to run.
Works with dotnet fsi command.
Does not work.
- OS: Windows 11 64bit
- Vim's version: Vim 8.2.4748
- Plugin's version: ac177bdf8198709b0ac9f31308e24d25f7ff22c7

Fix fsharp to use dotnet fsi

---

autoload/quickrun.vim

Running Rust on Windows does not work because `-o` does not append `.exe` automatically.

Fix Rust on Windows
